---
version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/snake_Game

permissions:
  - object: /home/ec2-user/snake_Game
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      runas: root
      timeout: 300

  AfterInstall:
    - location: scripts/install_dependencies.sh
      runas: ec2-user
      timeout: 300

  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
      timeout: 300
